name: XP CI
# thing just stopped working literally cannot be assed
on: []

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0

    - uses: actions/checkout@v2.3.1

    - name: Download 7zip
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/7za.exe'
        file-name: '7zip.exe'

    - name: Download references
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/build_deps/References.zip'
        file-name: 'References.zip'

    - name: Extract Refs
      run: ./7zip.exe e References.zip -oReferences -r -y

    - name: Restore project
      run: dotnet restore -p:Configuration=Release

    - name: Build project
      shell: pwsh
      run: |
        if ('${{ GITHUB.REF }}' -Match 'dev$') {
           dotnet build -p:DeployToServer=false -p:Configuration=Release -p:BuildNumber=${{ GITHUB.RUN_NUMBER }}
        } else {
           dotnet build -p:DeployToServer=false -p:Configuration=Release
        }
      env:
        EXILED_REFERENCES: ${{ github.workspace }}/References

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Results
        path: XPSystem/bin/Release
